on: [push]

jobs:
  k6_local_test:
    name: k6 performance tests
    runs-on: ubuntu-latest
    container: docker://loadimpact/k6:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run test
        uses: k6io/action@v0.1
        with:
          filename: performance-tests/perf-test.js
        env:
          BASE_URL: http://host.docker.internal:3001
