name: Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        run: |
          npm ci
          npm run ci:backend
          npm run test:api
      - name: Persist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            mochawesome-report
            cypress/screenshots
            cypress/videos
